### ISSUE TITLE
Save incomplete

### ISSUE THREAD

**Issue by deusyss** [AntumDeluge/debreate#11]
Hi,

I'm facing issue on saved files. The save function is correctly working, but not the opening function. The informations are not correctly imported, and, except required informations on control screen, no fields are filled.

**Comment by AntumDeluge** [comment]
Could you post the contents of your saved project file? I'm unable to reproduce the problem.

Which version of Debreate are you using? 0.7.13?

**Comment by deusyss** [comment]
Thanks.
After your message i retry. After a reboot and some OS update of my LinuxMint, no more problem. It was a fresh install of LM for quick use.

For information also, it was 0.7.13 debreate on Linux Mint 18.1 (fresh install). No error message was  displayed (i tried launching via terminal with and without sudo). Simply OS updates was necessary.

Sorry for this, and thanks for your quick help.

**Comment by AntumDeluge** [comment]
Thank you. I am glad that it is working correctly for you.
