### ISSUE TITLE
Where can I find the install list?

### ISSUE THREAD

**Issue by gaining** [AntumDeluge/debreate#15]
Hello, thanks for your software, it definitely makes life easier. It's just that after a deb file has been created and I extract it to view the content, I cannot find the install file containing the manifest of the app.

Basically, it's a list similar to:

app /usr/bin/
app-s /usr/bin/
app.py /usr/bin/
app.desktop /usr/share/applications/
share/icons/app.png /usr/share/icons/hicolor/48x48/actions/

**Comment by AntumDeluge** [comment]
I apologize for not responding sooner. I haven't been active with Debreate much over the past year.

I'm not familiar with a manifest file for deb packages, but I will look into it. There is an option to create an MD5 hash file when you build the package. Not sure if that is what you are looking for though. It should be located in the "DEBIAN" sub-directory when you extract.

**Comment by gaining** [comment]
Yeah that works too :smiley:
