### ISSUE TITLE
Uploading *.deb from debreate to launchpad ppa

### ISSUE THREAD

**Issue by ankitgyawali** [AntumDeluge/debreate#17]
Thanks for creating such a handy tool, really helpful in understanding how deb packaging works! I was wondering if there was any recommended way of uploading the deb file created from debreate to Launchpad ppa? I was not able to find any metadata created during deb creation from debreate inside my [deb file](https://github.com/ankitgyawali/crypto-indicator/tree/master/dist).

**Comment by AntumDeluge** [comment]
Actually, Launchpad only supports uploading source packages. Currently, Debreate only outputs binary .debs. I plan to implement source packaging, but it's somewhat complicated because of all the different build systems used by different software.

**Comment by ankitgyawali** [comment]
i ended up serving the deb file directly from github repo, i will have to look into creating debs directly from the canon dpkg next time im releasing something for linux, i just couldnt be bothered for this project. thanks again for your efforts with debreate, wish you best times ahead
