### ISSUE TITLE
Install files into user's folder?

### ISSUE THREAD

**Issue by vrybant** [AntumDeluge/debreate#18]
Thank you for great software! 

How to install files into current user's folder? When I'm  trying "~/" in the files section it's failed.

**Comment by AntumDeluge** [comment]
This was asked before, but I forgot where I gave the answer.

It is currently impossible to install files into a user's home directory via .deb package. The Debian package management system does not allow it.

The only way I know how to do it is to create a script that copies the files from the system directories to a user's home. If this only needs to be done for a single user, you can use a *postinstall* script. But if the files need to be installed for multiple users, I would put a script in the .deb package that installs to the system PATH, like */usr/bin*. Then, each user simply runs that script to automatically copy all related files to that user's home directory.
