### ISSUE TITLE
Debreate not running on Linux Mint 18.3 (64-bit)

### ISSUE THREAD

**Issue by vrybant** [AntumDeluge/debreate#19]
But fine running on Linux Mint 18.3 (**32-bit**)

**Comment by AntumDeluge** [comment]
I've been running it on Linux Mint 64-bit. Do you have traceback output?

**Comment by vrybant** [comment]
Where I can find traceback output?
I installed Debreate on pure Linux Mint in Virtual Box.
I was trying to run it from command line in /usr/bin and it is running with this message:

INFO: [debreate] Python version: 2.7.12
INFO: [debreate] wx.Python version: 3.0.2
INFO: [debreate] Debreate version: 0.7.13-dev16
INFO: [debreate] Logging level: 2

But when I am trying to run program from Menu - it failed (no respond)

**Comment by AntumDeluge** [comment]
The traceback would have shown in the command line. But if there was no error output, & you can't run it from the menu, then it sounds like maybe the menu launcher is corrupted.

You are using a development version. I may need to check it for a corrupt launcher file. Have you tried uninstalling & reinstalling? Can you get the stable version to run from the menu?

**Comment by vrybant** [comment]
I was trying before stable version too with same result.

But today I downloaded fresh image of Mint 18.3(64bit) and install it in Virtual Box.
Then I downloaded stable version of Debreate and now it works fine!

**Comment by AntumDeluge** [comment]
That's interesting. And Debreate was the only menu item that wasn't working? All your other programs launched from the menu?

**Comment by vrybant** [comment]
All other programs launched fine. But both version of Debreate (stable and development) did't launch from Menu but only from command line in that virtual mashine. May be some problem with Mint? Tomorrow I will install Mint from old downloaded image and let you know results.

**Comment by vrybant** [comment]
I reinstalled Mint from old downloaded image and install Debreate (stable) and now it works fine. May be that was conflict with some software installed on Linux before Debreate..

**Comment by AntumDeluge** [comment]
I'm glad it's working. If you end up installing the unstable development version, please let me know if you run into the same problem as before.
