### ISSUE TITLE
Dependancies problem?

### ISSUE THREAD

**Issue by GW3TMH** [AntumDeluge/debreate#20]
I am not sure if this is a bug or not, I am using Linux Mint 18, 64 bit XFCE with Python 2.7.12. You're about box on Debreate says I have Python 2.7.12 and wxPython 3.0.2 on the Sytem information tab.

As a minimal example if I put my dependency to "python=2.7.12" and try a test install it tells me my dependency has not been met, it works on the >= 2.7 though

I cannot get it to recognize any version of wxPython even if I say any wxPython > 2.6 it just says dependency not met. I can send screen shots.

Ken

**Comment by LanderU** [comment]
Could this link help you? https://wiki.wxpython.org/How%20to%20install%20wxPython

**Comment by AntumDeluge** [comment]
The wxPython package is not labelled "wxPython" in Debian/Ubuntu/Mint. It is [python-wxgtk2.8](https://packages.ubuntu.com/trusty/python-wxgtk2.8), [python-wxgtk3.0](https://packages.ubuntu.com/artful/python-wxgtk3.0), or [python-wxgtk4.0](https://packages.ubuntu.com/bionic/python-wxgtk4.0). Not sure why the *python* dependency isn't working. Perhaps try "[python2.7](https://packages.ubuntu.com/artful/python2.7) = 2.7.12".

**Comment by AntumDeluge** [comment]
I will be closing this soon as I have not received any more responses.

**Comment by farhi** [comment]
PR #40 indicates more allowed versions for python.
