### ISSUE TITLE
Editable Dialog On Auto-Link Help Prompt

### ISSUE THREAD

**Issue by matthew17754** [AntumDeluge/debreate#25]
I take it this wasn't meant to be editable so I figured I'd report it.
Reported on Version 0.7.1.3
Great software btw

![screenshot from 2018-08-31 20-11-37](https://user-images.githubusercontent.com/14935352/44949401-3bf79f00-ade5-11e8-8318-816fc5f78348.png)

**Comment by AntumDeluge** [comment]
Oh, ya. That's not supposed to be editable. Thank you for the report.

I really wish I had more time to work on this project. Hopefully I will be able to get a new Linux computer set up soon.

**Comment by AntumDeluge** [comment]
Fixed with commit 6d04667
