### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [AntumDeluge/debreate#35]
Hello!

I found link to this project from https://habr.com/ru/company/itsoft/blog/551556/

Could you please add information about license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by AntumDeluge** [comment]
Debreate is open source under the [MIT license](https://github.com/AntumDeluge/debreate/blob/master/docs/LICENSE.txt).

**Comment by vazhnov** [comment]
@AntumDeluge , could you please add this information into root `README.md` or into root `LICENSE` file?

**Comment by AntumDeluge** [comment]
I will do that. I thought I already had the license info in the README. But you're right, it's not there.

**Comment by vazhnov** [comment]
Great! Thank you!
