### ISSUE TITLE
debreate : Depends: python-wxgtk2.8 but it is not installable

### ISSUE THREAD

**Issue by SunyataZero** [AntumDeluge/debreate#6]
I tried to install debreate on my system (Ubuntu 16.04) and got the following error message

```
sunyata@sunyata-Aspire-ES1-131:~/PycharmProjects$ sudo apt install debreate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 debreate : Depends: python-wxgtk2.8 but it is not installable
E: Unable to correct problems, you have held broken packages.
sunyata@sunyata-Aspire-ES1-131:~/PycharmProjects$
```

---

Doing a search (`sudo apt-cache search python-wxgtk`) i found that the package `python-wxgtk3.0` is available in the official repo, maybe just updating to allow versions later than 2.8 will solve this issue?

**Comment by AntumDeluge** [comment]
Yes, the older versions use 2.8. I am trying to get a release out that supports 3.0, but it is taking longer than I thought it would. I think I will go back to last release & update it to get a new release out quicker. If you don't wan to wait, it is possible to get the old versions working in your Ubuntu distro. You just have to add a repo from an older Ubuntu release to your /etc/apt/sources.list. I think the last [Ubuntu release to support python-wxgtk2.8 was Trusty (14.04)](http://packages.ubuntu.com/trusty/python-wxgtk2.8).

The current unstable version support wxgtk3.0, but it is not fully functional nor ready for release.

**Comment by AntumDeluge** [comment]
I've decided to branch off the old version & get ready to release 0.7.12 with wx 3.0 compatibility. I haven't tested it thoroughly yet, but you can try it out if you like: [0.7 branch](https://github.com/AntumDeluge/debreate/tree/0.7)

After you download it, open a terminal in the root directory & issue the command:

`make debuild`

Then you can install the deb package and test it out.

There won't be any major changes from 0.7.11. It's only a quick release to support the newer wx versions.

**Comment by AntumDeluge** [comment]
I've opened a [PPA for development releases](https://launchpad.net/~antumdeluge/+archive/ubuntu/debreate-dev). Version 0.7.12-dev1 is the current release, so you can install it from there once the package successfully builds on Launchpad.

`sudo add-apt-repository ppa:antumdeluge/debreate-dev`

**Comment by SunyataZero** [comment]
Thank you for the response,

I installed the dev version of Debreate using the ppa above, but i don't get further than this screen:
![image](https://cloud.githubusercontent.com/assets/10245688/19347532/8d1e49b6-9149-11e6-861c-b46e502e3083.png)

When clicking on OK nothing happens

Here is stdout:
```
sunyata@sunyata-Aspire-ES1-131:~$ debreate
Python version: 2.7.12
wxPython version: 3.0.2
Debreate version: 0.7.12
Config not found, launching "First Run"
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
```

***

By the way, i am myself a bit of a front-end coder with an interest in Python and would be happy to look into this if you want? I also have some other skills (manual testing, documentation) that may be useful. If you are interested you can reach me at tord (dot) dellsen (at) gmail (dot) com

**Comment by SunyataZero** [comment]
Thank you for your response,
i needed to restart the software but now it seems to work! Very useful piece of software, i feel much more comfortable doing packaging using your GUI

***

By the way, i am myself a bit of a front-end coder with an interest in Python and would be happy to contribute to the project if there's anything you need help with? I also have some other skills besides programming (manual testing, documentation) that may be useful. If you are interested you can reach me at tord (dot) dellsen (at) gmail (dot) com

**Comment by AntumDeluge** [comment]
Thank you, I always appreciate help. I've been working pretty heavily on cleaning up the code & trying to get it ready for the 0.8.0 release. There is a [TODO](https://github.com/AntumDeluge/debreate/blob/unstable/docs/TODO.txt) list that shows what I'm doing.

It's interesting that you mention documentation. I've seen quite a few discussions that complain about not knowing how to use the GUI. I did make a YouTube video tutorial for an older release that the GUI links to, so I think there hasn't been quite as many complaints. But I'm trying to come up with some decent written documentation. I want to get rid of the old .pdf manual that is distributed with it.

I've also been documenting the code with [Doxygen](http://www.doxygen.org/), but that is more for myself & anyone that wants to contribute rather than end-users.

**Comment by AntumDeluge** [comment]
Also, I'm not always very active with the project. So I apologize if I am hard to get a hold of at times.

**Comment by SunyataZero** [comment]
If you like i can start by giving suggestions for the user documentation while i use debreate myself for another project i'm working on. How does this sound? Then i'll be coming from a user perspective which is so important in my experience. (Later on i could maybe do some coding as well as i start to understand packaging better)

**Comment by AntumDeluge** [comment]
That would be great.

**Comment by SunyataZero** [comment]
Hi, when trying to install from the main ppa or .deb files on the website i still get the same error, has the changes been put into the main branch yet?

**Comment by AntumDeluge** [comment]
What problem are you having? The software won't start up?

**Comment by SunyataZero** [comment]
It's just the same as when i created this issue:
```
sunyata@sunyata-Aspire-ES1-131:~$ sudo apt-get install debreate
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 debreate : Depends: python-wxgtk2.8 but it is not installable
E: Unable to correct problems, you have held broken packages.
sunyata@sunyata-Aspire-ES1-131:~$ 
```
I'm thinking that if changes have been made they may not have been merged into the main branch / trunk yet?

**Comment by AntumDeluge** [comment]
It appears to me that the problem you are having is with your package manager. I'm guessing that the broken packages on your system are causing you to be unable to upgrade to the newer version in the PPA.

Which version of Debreate is installed on your system? The current release in the development PPA is 0.7.12-dev2. I've had the issue where I couldn't close the opening window with 0.7.12-dev1. But I tested 0.7.12-dev2 to be working. If this is not the case, I will have another look into it.

Do you know how to fix the broken packages on your system? I would have to look it up as I don't remember at the moment.

**Comment by SunyataZero** [comment]
Just to be clear: The issue i am having is for the main version of the software, not the dev version. The dev version is probably working ok, but i thought that the bugs/issues in the issue list here on github was for the main version which is available on the website to download, have i misunderstood something? I thought you'd wait with closing this issue until the fix was in the main branch/trunk and the files on the website https://antumdeluge.github.io/debreate-web/ was uupdated). Kind Regards, Tord

**Comment by AntumDeluge** [comment]
Okay, I'm sorry. No, I haven't merged into main version yet. I want to be able to test more to make sure I got all bugs out before merging to main repository. I'll leave this issue open until  do that to avoid confusion in the future.

**Comment by AntumDeluge** [comment]
Version [0.7.12](https://github.com/AntumDeluge/debreate/releases/tag/v0.7.12) is released.

**Comment by SunyataZero** [comment]
Alright, i've also verified that this is working. Thank you for creating this important software. Kind Regards, Tord
