### ISSUE TITLE
[Feature Request] Suggustion

### ISSUE THREAD

**Issue by mmtrt** [AntumDeluge/debreate#9]
First of all geat application, I been loving it and just found Big Thanks to @LanderU 
I know it has custom path options but I use script to convert & resize then put images according to their size.
Because I've to manually add each folder name with its path respectively.

* Add folder with target path

(This adds files inside of selected folder and also adds it path to stored target path of each files separately)

**Comment by AntumDeluge** [comment]
Thank you. This is a bug that appeared in the last release. It has been fixed in commit 9eb138a & will be available in release 0.7.13.

**Comment by mmtrt** [comment]
@AntumDeluge Thanks I didn't know it was as a bug, Just install this app today.

**Comment by AntumDeluge** [comment]
[0.7.13 released](../releases/tag/v0.7.13).
